#!/usr/bin/env bash

# A script to create the gold files for the topocalc tests
# which requires the latest IPW version v2.4.1
#
# Run as:
#     $ ./tests/Lakes/gold_ipw/topocalc/make_gold_topocalc


read -r -p "Recreating gold topocalc standard, are you sure? [y/N] " response
if [[ "$response" = "yes" || "$response" = "y" ]]
then
    echo "Updating topocalc gold files"
    echo "Removing old gold files"
    rm tests/Lakes/gold_ipw/topocalc/*.ipw
    
    echo "Running IPW topocalc 16 angles"
    $IPW/bin/topocalc tests/Lakes/gold_ipw/gold_dem.ipw > tests/Lakes/gold_ipw/topocalc/topocalc_8bit_16ang.ipw

    echo "Running IPW topocalc 32 angles"
    $IPW/bin/topocalc -x tests/Lakes/gold_ipw/gold_dem.ipw > tests/Lakes/gold_ipw/topocalc/topocalc_8bit_32ang.ipw

else
    echo "Lakes gold files not updated"
fi